"""
backend/ai_interpretation/pii_scrubber.py
==========================================
Scrubs Personally Identifiable Information (PII) from kundli prompt strings
before they are sent to any LLM (Claude / OpenAI / etc.).

What is removed / anonymised
-----------------------------
  Name         → replaced with "the native"
  Full DOB     → replaced with birth year only (age context preserved)
  Birth place  → replaced with lat/lon only (removes city/country name)
  Lat/Lon      → rounded to 1 decimal place (city-level precision only)

The scrubbed prompt is safe to send to external LLM APIs.
No PII is ever logged or transmitted to third-party services.

Usage
-----
    from backend.ai_interpretation.pii_scrubber import scrub_prompt

    safe_prompt = scrub_prompt(kundli_prompt_string)

Architecture note
-----------------
  The raw kundli prompt may be generated by PyJHora's claude_formatter or by
  our own format_for_claude_compact() fallback. Both formats produce:
    "Name      : <name>"
    "Date      : YYYY-MM-DD"
    "Place     : <city>"
    "Lat/Lon   : <lat> / <lon>"  or  "Lat/Lon   : <lat>, <lon>"
  This scrubber handles both separator variants and any trailing whitespace.
"""
from __future__ import annotations

import re
import hashlib
from typing import Optional


# ── Regex patterns (case-insensitive, match the formatter output lines) ───────

_NAME_PATTERN = re.compile(
    r"^(\s*Name\s*:\s*)(.+)$",
    re.IGNORECASE | re.MULTILINE,
)

_DATE_PATTERN = re.compile(
    r"^(\s*Date\s*:\s*)(\d{4})-(\d{2})-(\d{2})(.*)$",
    re.IGNORECASE | re.MULTILINE,
)

_DATE_ALT_PATTERN = re.compile(
    r"^(\s*Date\s*of\s*Birth\s*:\s*)(\d{4})-(\d{2})-(\d{2})(.*)$",
    re.IGNORECASE | re.MULTILINE,
)

_PLACE_PATTERN = re.compile(
    r"^(\s*Place\s*:\s*)(.+)$",
    re.IGNORECASE | re.MULTILINE,
)

_LATLON_PATTERN = re.compile(
    r"^(\s*Lat/Lon\s*:\s*)([-\d.]+)\s*[/,]\s*([-\d.]+)(.*)$",
    re.IGNORECASE | re.MULTILINE,
)

_TOB_PATTERN = re.compile(
    r"^(\s*Time\s*:\s*)(.+)$",
    re.IGNORECASE | re.MULTILINE,
)


def _round_coord(coord_str: str, precision: int = 1) -> str:
    """Round a coordinate string to `precision` decimal places."""
    try:
        val = float(coord_str)
        return str(round(val, precision))
    except ValueError:
        return coord_str


def scrub_prompt(prompt: str, native_id: Optional[str] = None) -> str:
    """
    Scrub PII from a kundli prompt string.

    Parameters
    ----------
    prompt     : Raw kundli prompt (output of format_for_claude / format_for_claude_compact)
    native_id  : Optional stable anonymous identifier (e.g. profile_id[:8]) to include
                 so the LLM can distinguish multi-person readings without knowing the name.

    Returns
    -------
    Scrubbed prompt string safe for transmission to external LLM APIs.
    """
    if not prompt:
        return prompt

    alias = f"Native-{native_id[:8]}" if native_id else "the native"

    # 1. Replace name → alias
    prompt = _NAME_PATTERN.sub(
        lambda m: m.group(1) + alias,
        prompt,
    )

    # 2. Replace full DOB → year only
    def _redact_date(m: re.Match) -> str:
        year = m.group(2)
        rest = m.group(5)
        return m.group(1) + year + rest  # keep prefix, year, and any trailing content

    prompt = _DATE_PATTERN.sub(_redact_date, prompt)
    prompt = _DATE_ALT_PATTERN.sub(_redact_date, prompt)

    # 3. Remove time of birth (can identify individuals within a day)
    prompt = _TOB_PATTERN.sub(
        lambda m: m.group(1) + "[redacted]",
        prompt,
    )

    # 4. Replace city/place → "[location omitted]"
    prompt = _PLACE_PATTERN.sub(
        lambda m: m.group(1) + "[location omitted]",
        prompt,
    )

    # 5. Round lat/lon to 1 decimal (≈11 km precision — city-level only)
    def _round_latlon(m: re.Match) -> str:
        lat = _round_coord(m.group(2))
        lon = _round_coord(m.group(3))
        rest = m.group(4)
        return m.group(1) + lat + " / " + lon + rest

    prompt = _LATLON_PATTERN.sub(_round_latlon, prompt)

    return prompt



def scrub_profile(profile: dict) -> dict:
    """
    Return a copy of a profile dict with PII keys removed/anonymised.
    Safe to pass as additional context to LLM calls.

    Keys removed: name, date_of_birth, time_of_birth, place_of_birth, email
    Keys kept:    language, region, marital_status, gender, predictions_json,
                  chart-level keys (lagna, ascendant, sun_sign, moon_sign, etc.)
    """
    safe_keys = {
        "language", "preferred_language", "region", "currency",
        "marital_status", "gender", "kundli_json", "predictions_json",
        "refined_analysis", "dasha_json", "user_type",
        # Chart-level keys that may be top-level in some profile shapes
        "lagna", "ascendant", "sun_sign", "moon_sign", "birth_year",
        "navamsa", "planets", "houses", "yoga_list", "dasha_periods",
    }
    safe = {k: v for k, v in profile.items() if k in safe_keys}

    # Keep birth year only (for age estimation)
    dob = profile.get("date_of_birth", "")
    if dob and len(dob) >= 4:
        safe["birth_year"] = dob[:4]

    return safe
